version: 2
jobs:
  build:
    docker:
      - image: cppchriscpp/cc65-node:latest
    steps:
      - checkout
      - run:
          name: Move tools folder to expected location
          command: cp -rf /tools .
      - run:
          name: "Npm installs"
          command: "cd tools/tmx2c/src && npm install && cd ../../../tools/sprite_def2img/src && npm install && cd ../../../tools/chr2img/src && npm install"
      - run:
          name: Build the game itself
          command: make
      - store_artifacts:
          path: ./rom
workflows:
  version: 2
  build:
    jobs: 
      - build
